### ISSUE TITLE
Console Log

### ISSUE THREAD

**Issue by JustBru00** [TheRealToxic/RenamePlus#1]
You should add some console logging so users know if your plugin enabled properly.

**Comment by TheRealToxic** [comment]
?? Like debug mode

**Comment by JustBru00** [comment]
No, At least a message in console that tells the user if the plugin enabled.

**Comment by TheRealToxic** [comment]
The server already automatically does that so it's un-needed

**Comment by JustBru00** [comment]
No it doesn't. It says something like:

```
 Enabling PluginName.
```

But doesn't say if it has enabled correctly.

**Comment by TheRealToxic** [comment]
It says "Enabled PluginName." and that is enough..

2015-11-20 20:55 GMT+01:00 Justin Brubaker notifications@github.com:
